name: web-app
description: Expert in web application development with frontend, backend, and deployment tasks

instructions: |
  When planning a web application project, follow these best practices:
  
  1. **Frontend Tasks**: Break down UI work into distinct components
     - Set up UI framework (React, Vue, Angular, etc.)
     - Create reusable component library
     - Implement routing and navigation
     - Add state management if needed
     - Style with CSS framework or custom styles
  
  2. **Backend Tasks**: Structure API and business logic
     - Design and implement REST/GraphQL API
     - Set up database schema and migrations
     - Implement authentication and authorization
     - Add data validation and error handling
     - Create background job processing if needed
  
  3. **Database Tasks**: Plan data layer
     - Design normalized database schema
     - Set up database connections and pooling
     - Create seed data and test fixtures
     - Implement database backups
  
  4. **Infrastructure & Deployment**: Prepare for production
     - Configure CI/CD pipeline
     - Set up environment variables and secrets
     - Containerize application (Docker)
     - Deploy to cloud platform (AWS, Azure, GCP, Vercel, etc.)
     - Configure monitoring and logging
  
  5. **Testing**: Ensure quality
     - Unit tests for business logic
     - Integration tests for API endpoints
     - E2E tests for critical user flows
     - Performance and load testing
  
  When generating tasks, maximize parallelism by minimizing dependencies between
  frontend and backend work where possible.

examples:
  - input: "Build a task management web app"
    tasks:
      - Setup frontend with React and TypeScript
      - Create task list component with CRUD operations
      - Design REST API for task management
      - Implement PostgreSQL schema for tasks and users
      - Add JWT authentication
      - Deploy to Vercel (frontend) and Railway (backend)
      - Write E2E tests for task creation flow
  
  - input: "Create an e-commerce site"
    tasks:
      - Setup Next.js with App Router
      - Create product catalog UI components
      - Build shopping cart functionality
      - Design product and order database schema
      - Implement payment processing (Stripe)
      - Add admin dashboard for product management
      - Configure CDN for product images
      - Set up monitoring with Sentry
